In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('cars.csv')

#Display the first few rows of the dataset
#print(df.head())
df

,year,make,model,trim,body,transmission,vin,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2002,vw,jetta,gls 1.8t,NaN,NaN,3vwse29m02m183926,123304.0,black,NaN,era classic auto sales ltd,1425.0,2150.0,Thu Dec 18 2014 18:30:00 GMT-0800 (PST)
1,2011,vw,jetta,comfrtline,NaN,NaN,3vwdl7ajxbm007124,80150.0,black,black,vw credit canada inc,9850.0,13400.0,Tue Jan 06 2015 02:00:00 GMT-0800 (PST)
2,2014,vw,routan,se,NaN,automatic,2c4rvabg5er135156,13556.0,black,gray,vw credit,21000.0,22200.0,Tue Jan 13 2015 10:00:00 GMT-0800 (PST)
3,1999,vw,beetle,gls tdi,NaN,manual,3vwcf21c7xm463810,276953.0,blue,gray,burnsville volkswagen inc,1125.0,1500.0,Thu Dec 18 2014 10:45:00 GMT-0800 (PST)
4,2011,vw,jetta,comfrtline,NaN,NaN,3vwdk7aj4bm008711,110754.0,blue,black,vw credit canada inc,8600.0,8400.0,Tue Jan 06 2015 02:00:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,2013,Acura,RDX,Technology Package,suv,automatic,5j8tb4h51dl015921,32483.0,white,beige,honda r&d americas inc,28100.0,29000.0,Fri Jun 19 2015 05:00:00 GMT-0700 (PDT)
558833,2014,Acura,RDX,Technology Package,suv,NaN,5j8tb4h59el001279,15960.0,white,beige,adcock brothers inc,32500.0,33000.0,Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
558834,2011,Acura,RDX,SH-AWD,suv,automatic,5j8tb1h21ba001806,79007.0,white,black,congers auto sales inc,16150.0,16500.0,Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
558835,2012,Acura,MDX,Base,suv,NaN,2hnyd2h26ch527236,18538.0,white,tan,adcock brothers inc,27600.0,28600.0,Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
558836,2013,Acura,TSX,Base,sedan,automatic,jh4cu2f42dc000429,17247.0,white,beige,acura of las vegas,20800.0,21200.0,Fri Jun 19 2015 04:55:00 GMT-0700 (PDT)

In [2]:
df.isnull().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
odometer           94
color           25460
interior        17826
seller              0
mmr                12
sellingprice       12
saledate           38
dtype: int64

In [3]:
df = df.dropna()
df1 = df.reset_index(drop=True)
df1

,year,make,model,trim,body,transmission,vin,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Volvo,XC70,T6,Wagon,automatic,yv4902nb3f1196951,12725.0,beige,beige,volvo na rep/world omni,32300.0,32500.0,Thu Feb 12 2015 04:30:00 GMT-0800 (PST)
1,2005,Volvo,XC90,T6,SUV,automatic,yv1cz911751162959,107449.0,beige,beige,jpmorgan chase bank n.a.,5325.0,5600.0,Thu Dec 18 2014 09:20:00 GMT-0800 (PST)
2,2004,Volvo,XC90,T6,SUV,automatic,yv1cz91h541092227,139564.0,beige,beige,paul anthony auto group llc,3400.0,2800.0,Thu Dec 18 2014 10:00:00 GMT-0800 (PST)
3,2003,Volvo,XC70,Base,Wagon,automatic,yv1sz59h631098609,175011.0,beige,gray,luxury imports auto sales inc,1475.0,1100.0,Thu Dec 18 2014 10:45:00 GMT-0800 (PST)
4,2002,Volvo,S80,2.9,Sedan,automatic,yv1ts92d821269690,107963.0,beige,gray,pohanka acura,1775.0,2000.0,Thu Dec 18 2014 09:50:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446234,2012,Acura,MDX,Technology Package,suv,automatic,2hnyd2h3xch515972,26260.0,white,tan,braman motors,29600.0,28000.0,Wed Jun 17 2015 17:00:00 GMT-0700 (PDT)
446235,2010,Acura,RDX,Base,suv,automatic,5j8tb2h53aa004835,54251.0,white,black,high bid trading co inc,17050.0,15750.0,Wed Jun 17 2015 05:15:00 GMT-0700 (PDT)
446236,2013,Acura,RDX,Technology Package,suv,automatic,5j8tb4h51dl015921,32483.0,white,beige,honda r&d americas inc,28100.0,29000.0,Fri Jun 19 2015 05:00:00 GMT-0700 (PDT)
446237,2011,Acura,RDX,SH-AWD,suv,automatic,5j8tb1h21ba001806,79007.0,white,black,congers auto sales inc,16150.0,16500.0,Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
446238,2013,Acura,TSX,Base,sedan,automatic,jh4cu2f42dc000429,17247.0,white,beige,acura of las vegas,20800.0,21200.0,Fri Jun 19 2015 04:55:00 GMT-0700 (PDT)

In [4]:
from sklearn.preprocessing import LabelEncoder

# Define the list of columns to encode
columns_to_encode = ['color', 'interior', 'transmission', 'make']

for column in columns_to_encode:
    # Initialize LabelEncoder for each column
    encoder = LabelEncoder()
    # Convert NaNs to string and apply label encoding
    df1[column] = encoder.fit_transform(df1[column].astype(str))

    # Get unique categories and their corresponding encoded numbers
    categories_mapping = dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))

    # Find the maximum length of category name for proper alignment
    max_length = max(len(str(category)) for category in categories_mapping.keys())

    # Print the mappings with proper alignment
    print(f"\n{column.capitalize()} Encodings:")
    for category, encoded_number in categories_mapping.items():
        print(f"{str(category).ljust(max_length)} assigned as {encoded_number}")

# Now df contains the original columns updated with encodings
# You can access and use the updated DataFrame 'df' for further analysis or modeling

Color Encodings:
beige     assigned as 0
black     assigned as 1
blue      assigned as 2
brown     assigned as 3
burgundy  assigned as 4
charcoal  assigned as 5
gold      assigned as 6
gray      assigned as 7
green     assigned as 8
lime      assigned as 9
off-white assigned as 10
orange    assigned as 11
pink      assigned as 12
purple    assigned as 13
red       assigned as 14
silver    assigned as 15
turquoise assigned as 16
white     assigned as 17
yellow    assigned as 18

Interior Encodings:
beige     assigned as 0
black     assigned as 1
blue      assigned as 2
brown     assigned as 3
burgundy  assigned as 4
gold      assigned as 5
gray      assigned as 6
green     assigned as 7
off-white assigned as 8
orange    assigned as 9
purple    assigned as 10
red       assigned as 11
silver    assigned as 12
tan       assigned as 13
white     assigned as 14
yellow    assigned as 15

Transmission Encodings:
automatic assigned as 0
manual    assigned as 1

Make Encodings:
Acura         assigned as 0
Aston Martin  assigned as 1
Audi          assigned as 2
BMW           assigned as 3
Bentley       assigned as 4
Buick         assigned as 5
Cadillac      assigned as 6
Chevrolet     assigned as 7
Chrysler      assigned as 8
Daewoo        assigned as 9
Dodge         assigned as 10
FIAT          assigned as 11
Ferrari       assigned as 12
Fisker        assigned as 13
Ford          assigned as 14
GMC           assigned as 15
Geo           assigned as 16
HUMMER        assigned as 17
Honda         assigned as 18
Hyundai       assigned as 19
Infiniti      assigned as 20
Isuzu         assigned as 21
Jaguar        assigned as 22
Jeep          assigned as 23
Kia           assigned as 24
Lamborghini   assigned as 25
Land Rover    assigned as 26
Lexus         assigned as 27
Lincoln       assigned as 28
Lotus         assigned as 29
MINI          assigned as 30
Maserati      assigned as 31
Mazda         assigned as 32
Mercedes-Benz assigned as 33
Mercury       assigned as 34
Mitsubishi    assigned as 35
Nissan        assigned as 36
Oldsmobile    assigned as 37
Plymouth      assigned as 38
Pontiac       assigned as 39
Porsche       assigned as 40
Ram           assigned as 41
Rolls-Royce   assigned as 42
Saab          assigned as 43
Saturn        assigned as 44
Scion         assigned as 45
Subaru        assigned as 46
Suzuki        assigned as 47
Tesla         assigned as 48
Toyota        assigned as 49
Volkswagen    assigned as 50
Volvo         assigned as 51
smart         assigned as 52

In [5]:
df1.to_csv('final2.csv')
final = pd.read_csv('final2.csv', index_col = 0)
final

,year,make,model,trim,body,transmission,vin,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,51,XC70,T6,Wagon,0,yv4902nb3f1196951,12725.0,0,0,volvo na rep/world omni,32300.0,32500.0,Thu Feb 12 2015 04:30:00 GMT-0800 (PST)
1,2005,51,XC90,T6,SUV,0,yv1cz911751162959,107449.0,0,0,jpmorgan chase bank n.a.,5325.0,5600.0,Thu Dec 18 2014 09:20:00 GMT-0800 (PST)
2,2004,51,XC90,T6,SUV,0,yv1cz91h541092227,139564.0,0,0,paul anthony auto group llc,3400.0,2800.0,Thu Dec 18 2014 10:00:00 GMT-0800 (PST)
3,2003,51,XC70,Base,Wagon,0,yv1sz59h631098609,175011.0,0,6,luxury imports auto sales inc,1475.0,1100.0,Thu Dec 18 2014 10:45:00 GMT-0800 (PST)
4,2002,51,S80,2.9,Sedan,0,yv1ts92d821269690,107963.0,0,6,pohanka acura,1775.0,2000.0,Thu Dec 18 2014 09:50:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446234,2012,0,MDX,Technology Package,suv,0,2hnyd2h3xch515972,26260.0,17,13,braman motors,29600.0,28000.0,Wed Jun 17 2015 17:00:00 GMT-0700 (PDT)
446235,2010,0,RDX,Base,suv,0,5j8tb2h53aa004835,54251.0,17,1,high bid trading co inc,17050.0,15750.0,Wed Jun 17 2015 05:15:00 GMT-0700 (PDT)
446236,2013,0,RDX,Technology Package,suv,0,5j8tb4h51dl015921,32483.0,17,0,honda r&d americas inc,28100.0,29000.0,Fri Jun 19 2015 05:00:00 GMT-0700 (PDT)
446237,2011,0,RDX,SH-AWD,suv,0,5j8tb1h21ba001806,79007.0,17,1,congers auto sales inc,16150.0,16500.0,Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
446238,2013,0,TSX,Base,sedan,0,jh4cu2f42dc000429,17247.0,17,0,acura of las vegas,20800.0,21200.0,Fri Jun 19 2015 04:55:00 GMT-0700 (PDT)

In [6]:
final.isnull().sum()

year            0
make            0
model           0
trim            0
body            0
transmission    0
vin             0
odometer        0
color           0
interior        0
seller          0
mmr             0
sellingprice    0
saledate        0
dtype: int64

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


x = final[['year', 'transmission', 'odometer', 'color', 'interior', 'mmr', 'make']]
y = final['sellingprice']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

model = LinearRegression()
model.fit(x_train, y_train)
predictions = model.predict(x_test)

In [8]:
model.predict([[2015, 0, 139500, 3, 2, 23000, 0]])

/root/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22427.54447986])

In [9]:
model.predict([[2015, 0, 139500, 3, 2, 37000, 26]])

/root/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36307.92898909])

In [10]:
model.predict([[2010, 2, 12000, 3, 2, 33000, 1]])

/root/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([32341.10733304])

In [11]:
model.score(x_test,y_test)

0.9683399437648876